### ISSUE TITLE
Unable to load DLL 'libtensorflow'

### ISSUE THREAD

**Issue by SergeyKashkovsky** [lepeap/DeepMorphy#4]
Здравствуйте. Пытаюсь запустить на сервере winServer2016 (x64) и получаю такую ошибку:

```
An unhandled exception was thrown by the application.
System.DllNotFoundException: Unable to load DLL 'libtensorflow' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)
   at TensorFlow.TFGraph.TF_NewGraph()
   at TensorFlow.TFGraph..ctor()
   at DeepMorphy.NeuralNet.TfNeuralNet..ctor(IDictionary`2 opDic, IDictionary`2 gramOpDic, Boolean bigModel, Boolean withLemmatization)
   at DeepMorphy.NeuralNet.Processor..ctor(Int32 maxBatchSize, Boolean withLemmatization, Boolean useEnGrams, Boolean bigModel)
   at DeepMorphy.MorphAnalyzer..ctor(Boolean withLemmatization, Boolean useEnGrams, Boolean withTrimAndLower, Boolean withPreprocessors, Int32 maxBatchSize)
```

Пробовал выставить CPU x64, пробовал ставить отдельно TF - не помогает. Может, у вас есть какие-нибудь мысли по устранению ошибки? Спасибо.

**Comment by lepeap** [comment]
Здравствуйте. С ходу не могу так сказать.
А в журнале событий нет подробностей?  Можно попробовать посмотреть что-то в журнале, потому что ошибка не очень говорящая (может валиться по многим причинам и выкидывать такое сообщение).
Из возможных проблем (на мой взгляд, не особый спец по нативным сборкам в винде):
- какой-то очень старый процессор, который не поддерживает набор инструкций, с которыми скомпилирована данная tf dll. (тут можно погуглить, что за проц и попробовать скомпилировать tf c набором инструкций для него);
- не хватает чего-то из с++ экосистемы windows (какого-нить C++ Redistributable см: https://github.com/migueldeicaza/TensorFlowSharp/issues/322).

**Comment by SergeyKashkovsky** [comment]
В журнале только текст приведенной выше ошибки.
Разбираемся совместно с админом этого сервера. Напишу, если что получится.
